import { Atmosphere, FunLevel, ParkingLevel, TriState } from "./types";

export interface SeedPlace {
  neighborhoodId: string;
  name: string;
  category: string;
  address: string;
  description: string;
  kidsChair: TriState;
  atmosphere: Atmosphere;
  noKidsZone: 0 | 1;
  activities: string;
  kidsFood: TriState;
  kidsFoodNote: string;
  kidsFunLevel: FunLevel;
  parking: ParkingLevel;
  parkingNote: string;
  reviews?: {
    authorName: string;
    rating: number;
    childAge: string;
    content: string;
  }[];
}

// 실제 상호가 아닌 예시(샘플) 데이터입니다. 서비스 오픈 초기 화면이 비어 보이지 않도록
// 넣어둔 참고용 장소이며, 실제 제보/리뷰가 쌓이면 자연스럽게 뒤로 밀려납니다.
export const SEED_PLACES: SeedPlace[] = [
  {
    neighborhoodId: "seochon",
    name: "서촌 마당 한옥카페",
    category: "카페",
    address: "서울 종로구 자하문로 인근",
    description: "한옥을 개조한 마당 있는 카페. 마당에 아이가 뛰어놀 수 있는 공간이 있어요.",
    kidsChair: "yes",
    atmosphere: "welcoming",
    noKidsZone: 0,
    activities: "마당에서 자유롭게 뛰어놀기, 그림책 코너",
    kidsFood: "yes",
    kidsFoodNote: "요거트, 감자튀김, 미숫가루 등 자극적이지 않은 메뉴 있음",
    kidsFunLevel: "fun",
    parking: "none",
    parkingNote: "골목 안이라 주차 공간 없음, 대중교통 추천",
    reviews: [
      {
        authorName: "민준맘",
        rating: 5,
        childAge: "3세",
        content: "마당에서 뛰어노는 동안 저는 커피 마실 수 있어서 좋았어요. 사장님도 친절하세요.",
      },
    ],
  },
  {
    neighborhoodId: "seosullagil",
    name: "순라길 산책 디저트가게",
    category: "디저트/베이커리",
    address: "서울 종로구 돈화문로 인근",
    description: "종묘 돌담길 산책 후 들르기 좋은 작은 디저트 가게. 좌석이 많지 않아요.",
    kidsChair: "no",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "돌담길 산책, 포장 후 근처 공원 벤치 이용",
    kidsFood: "yes",
    kidsFoodNote: "우유, 아이스크림류",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "인근 공영주차장 도보 5분",
  },
  {
    neighborhoodId: "haebangchon",
    name: "해방촌 루프탑 브런치",
    category: "브런치 레스토랑",
    address: "서울 용산구 신흥로 인근",
    description: "언덕 위 루프탑 브런치집. 테이블 간격이 넓어 유아차 이동이 편해요.",
    kidsChair: "yes",
    atmosphere: "welcoming",
    noKidsZone: 0,
    activities: "루프탑에서 남산 전망 구경",
    kidsFood: "yes",
    kidsFoodNote: "감자, 계란요리 등 순한 메뉴 가능",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "경사로가 많아 유아차는 큰길 쪽 입구 이용 권장",
  },
  {
    neighborhoodId: "seongsu",
    name: "서울숲 피크닉 카페",
    category: "카페",
    address: "서울 성동구 서울숲길 인근",
    description: "서울숲 바로 앞, 통유리로 숲이 보이는 넓은 카페. 키즈 공간이 별도로 있어요.",
    kidsChair: "yes",
    atmosphere: "welcoming",
    noKidsZone: 0,
    activities: "서울숲 산책, 카페 내 키즈코너, 자전거 대여",
    kidsFood: "yes",
    kidsFoodNote: "키즈 메뉴판 따로 있음 (오므라이스, 주먹밥)",
    kidsFunLevel: "fun",
    parking: "good",
    parkingNote: "건물 지하주차장 2시간 무료",
    reviews: [
      {
        authorName: "하은아빠",
        rating: 5,
        childAge: "5세",
        content: "숲 산책하고 카페 들어가서 밥까지 해결. 주차도 편해서 자주 가요.",
      },
      {
        authorName: "지우맘",
        rating: 4,
        childAge: "18개월",
        content: "유아차 그대로 들어갈 수 있어서 좋았어요. 주말엔 좀 붐벼요.",
      },
    ],
  },
  {
    neighborhoodId: "magok",
    name: "마곡 식물원 앞 패밀리 레스토랑",
    category: "레스토랑",
    address: "서울 강서구 마곡동 인근",
    description: "서울식물원 바로 앞 대형 레스토랑. 룸 좌석과 아기의자가 넉넉해요.",
    kidsChair: "yes",
    atmosphere: "welcoming",
    noKidsZone: 0,
    activities: "서울식물원 온실 관람, 매장 내 놀이 매트 공간",
    kidsFood: "yes",
    kidsFoodNote: "이유식 데워주기 가능, 유아용 식기 제공",
    kidsFunLevel: "fun",
    parking: "good",
    parkingNote: "대형 몰 주차장 이용, 영수증 지참 시 할인",
  },
  {
    neighborhoodId: "yeonnam",
    name: "연남 숲길 브런치",
    category: "브런치 레스토랑",
    address: "서울 마포구 연남동 경의선숲길 인근",
    description: "경의선숲길 바로 옆 브런치집. 평일 오전엔 한적해요.",
    kidsChair: "unknown",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "숲길 자전거, 잔디밭에서 뛰어놀기",
    kidsFood: "unknown",
    kidsFoodNote: "제보가 더 필요해요",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "주변 골목 유료 주차 위주",
  },
  {
    neighborhoodId: "mangwon",
    name: "망원 한강뷰 카페",
    category: "카페",
    address: "서울 마포구 망원동 한강공원 인근",
    description: "한강공원 진입로 근처 통창 카페. 아이 자전거 타고 오기 좋아요.",
    kidsChair: "yes",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "한강공원 자전거, 돗자리 피크닉",
    kidsFood: "yes",
    kidsFoodNote: "주스, 크로플 등 아이 간식 위주",
    kidsFunLevel: "fun",
    parking: "ok",
    parkingNote: "한강공원 공영주차장 도보 이용",
  },
  {
    neighborhoodId: "euljiro",
    name: "을지로 뉴트로 술집거리 노포",
    category: "술집/포차",
    address: "서울 중구 을지로 골목",
    description: "저녁엔 어른 위주 술집 골목이라 아이 동반은 추천하지 않아요.",
    kidsChair: "no",
    atmosphere: "awkward",
    noKidsZone: 1,
    activities: "특별히 없음",
    kidsFood: "no",
    kidsFoodNote: "",
    kidsFunLevel: "boring",
    parking: "none",
    parkingNote: "골목 상권이라 주차 매우 어려움",
  },
  {
    neighborhoodId: "ikseondong",
    name: "익선동 한옥 티하우스",
    category: "카페",
    address: "서울 종로구 익선동 골목",
    description: "좁은 골목 안 한옥 카페. 좌석이 좁고 계단이 있어 유아차 진입이 어려워요.",
    kidsChair: "no",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "골목 구경, 소품샵 구경",
    kidsFood: "unknown",
    kidsFoodNote: "",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "주차 불가, 대중교통만 추천",
  },
  {
    neighborhoodId: "mullae",
    name: "문래 창작촌 아트카페",
    category: "카페 겸 갤러리",
    address: "서울 영등포구 문래동 철공소 골목",
    description: "철공소 골목 사이 예술 공간을 개조한 카페. 벽화 구경하며 산책하기 좋아요.",
    kidsChair: "unknown",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "골목 벽화 구경, 공방 체험(사전예약)",
    kidsFood: "unknown",
    kidsFoodNote: "",
    kidsFunLevel: "okay",
    parking: "ok",
    parkingNote: "골목 노상 주차, 저녁엔 혼잡",
  },
  {
    neighborhoodId: "hannam",
    name: "한남동 갤러리 카페",
    category: "카페 겸 갤러리",
    address: "서울 용산구 한남동",
    description: "조용한 분위기의 갤러리 카페. 전시품이 많아 아이와 함께면 눈치가 보일 수 있어요.",
    kidsChair: "no",
    atmosphere: "awkward",
    noKidsZone: 0,
    activities: "전시 관람(아이가 뛰면 제지될 수 있음)",
    kidsFood: "no",
    kidsFoodNote: "",
    kidsFunLevel: "boring",
    parking: "ok",
    parkingNote: "건물 내 소규모 주차장, 만차 잦음",
  },
  {
    neighborhoodId: "hapjeong",
    name: "합정 놀이터 딸린 카페",
    category: "카페",
    address: "서울 마포구 합정동",
    description: "매장 안에 작은 키즈존이 있는 동네 카페. 단골 가족이 많아요.",
    kidsChair: "yes",
    atmosphere: "welcoming",
    noKidsZone: 0,
    activities: "매장 내 미끄럼틀, 볼풀",
    kidsFood: "yes",
    kidsFoodNote: "치즈스틱, 감자튀김, 아이 음료",
    kidsFunLevel: "fun",
    parking: "none",
    parkingNote: "매장 앞 협소, 인근 공영주차장 이용",
    reviews: [
      {
        authorName: "서준이할머니",
        rating: 5,
        childAge: "4세",
        content: "손주랑 갔는데 키즈존에서 노는 동안 편하게 얘기 나눴어요. 강추합니다.",
      },
    ],
  },
  {
    neighborhoodId: "songridangil",
    name: "송리단길 파스타집",
    category: "레스토랑",
    address: "서울 송파구 석촌호수 인근",
    description: "석촌호수 산책 후 가기 좋은 파스타집. 테이블 간격이 좁은 편이에요.",
    kidsChair: "yes",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "석촌호수 산책, 오리배",
    kidsFood: "yes",
    kidsFoodNote: "토마토 파스타, 감자튀김 등 순한 메뉴",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "호수 공영주차장 도보 10분",
  },
  {
    neighborhoodId: "garosugil",
    name: "가로수길 플래그십 카페",
    category: "카페",
    address: "서울 강남구 신사동 가로수길",
    description: "쇼핑하다 들르기 좋은 넓은 플래그십 카페. 주말엔 대기가 길어요.",
    kidsChair: "yes",
    atmosphere: "neutral",
    noKidsZone: 0,
    activities: "가로수길 쇼핑, 포토존 구경",
    kidsFood: "unknown",
    kidsFoodNote: "",
    kidsFunLevel: "okay",
    parking: "none",
    parkingNote: "인근 사설 주차장 요금 비쌈",
  },
];
